import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F7F8FC" },
  topNav: { minHeight: 72, paddingTop: 24, paddingHorizontal: 20, alignItems: "center", justifyContent: "center", backgroundColor: "#293B51" },
  brand: { color: "#FFFFFF", fontSize: 18, fontWeight: "700", letterSpacing: 0.2 },
  content: { paddingBottom: 112 },
  profileSection: { alignItems: "center", paddingHorizontal: 24, paddingTop: 30, paddingBottom: 28, backgroundColor: "#FFFFFF" },
  avatarWrap: { width: 88, height: 88, marginBottom: 14, position: "relative" },
  avatar: { width: "100%", height: "100%", borderRadius: 44, alignItems: "center", justifyContent: "center", backgroundColor: "#3E5570", shadowColor: "#293B51", shadowOpacity: 0.22, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 5 },
  avatarText: { color: "#FFFFFF", fontSize: 28, fontWeight: "600" },
  onlineDot: { position: "absolute", right: 0, bottom: 2, width: 18, height: 18, borderRadius: 9, backgroundColor: "#46C88A", borderWidth: 3, borderColor: "#FFFFFF" },
  name: { color: "#172033", fontSize: 22, fontWeight: "600" },
  memberSince: { color: "#7C8495", fontSize: 13, marginTop: 4 },
  editButton: { height: 42, marginTop: 17, paddingHorizontal: 20, borderRadius: 12, flexDirection: "row", alignItems: "center", backgroundColor: "#293B51" },
  editIcon: { color: "#FFFFFF", fontSize: 16, marginRight: 8 },
  editButtonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "600" },
  section: { paddingHorizontal: 20, paddingTop: 24 },
  sectionTitle: { color: "#172033", fontSize: 16, fontWeight: "700", marginBottom: 12 },
  card: { borderRadius: 17, borderWidth: 1, borderColor: "#E9ECF3", backgroundColor: "#FFFFFF", paddingHorizontal: 16, overflow: "hidden" },
  cardTitle: { color: "#30394D", fontSize: 14, fontWeight: "700", marginTop: 16 },
  cardDescription: { color: "#8991A1", fontSize: 12, lineHeight: 18, marginTop: 5 },
  frequencyRow: { flexDirection: "row", gap: 7, marginTop: 14, marginBottom: 16 },
  frequencyOption: { flex: 1, minHeight: 36, paddingHorizontal: 5, borderRadius: 9, borderWidth: 1, borderColor: "#E3E6EF", alignItems: "center", justifyContent: "center" },
  frequencyOptionActive: { borderColor: "#293B51", backgroundColor: "#E8EDF3" },
  frequencyText: { color: "#7C8495", fontSize: 11, fontWeight: "600", textAlign: "center" },
  frequencyTextActive: { color: "#293B51" },
  notificationRow: { minHeight: 76, paddingVertical: 13, flexDirection: "row", alignItems: "center" },
  notificationDivider: { borderBottomWidth: 1, borderBottomColor: "#EEF0F5" },
  notificationIcon: { width: 38, height: 38, marginRight: 11, borderRadius: 11, alignItems: "center", justifyContent: "center", backgroundColor: "#E8EDF3" },
  unreadIcon: { backgroundColor: "#DCE4ED" },
  notificationIconText: { color: "#293B51", fontSize: 18, fontWeight: "700" },
  notificationCopy: { flex: 1, paddingRight: 8 },
  notificationTitle: { color: "#30394D", fontSize: 13, fontWeight: "600" },
  unreadTitle: { color: "#172033", fontWeight: "700" },
  notificationDescription: { color: "#8B93A3", fontSize: 11, lineHeight: 16, marginTop: 3 },
  historyHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  historyCount: { color: "#293B51", fontSize: 12, fontWeight: "700", backgroundColor: "#E8EDF3", borderRadius: 10, paddingHorizontal: 9, paddingVertical: 4, marginBottom: 12 },
  historyRow: { minHeight: 94, paddingVertical: 14, flexDirection: "row", alignItems: "flex-start" },
  historyCopy: { flex: 1 },
  historyTitleRow: { flexDirection: "row", alignItems: "center" },
  unreadDot: { width: 6, height: 6, marginLeft: 7, borderRadius: 3, backgroundColor: "#293B51" },
  historyMeta: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 7 },
  historyDate: { color: "#A0A7B4", fontSize: 10 },
  historyTime: { color: "#A0A7B4", fontSize: 10 },
  readStatus: { color: "#50A77A", fontSize: 10, fontWeight: "600" },
  unreadStatus: { color: "#293B51" },
  emptyState: { alignItems: "center", paddingHorizontal: 24, paddingVertical: 32 },
  emptyIcon: { color: "#71859B", fontSize: 30, marginBottom: 9 },
  emptyTitle: { color: "#30394D", fontSize: 14, fontWeight: "700" },
  emptyDescription: { color: "#8B93A3", fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 },
  bottomNav: { position: "absolute", left: 16, right: 16, bottom: 16, minHeight: 72, paddingHorizontal: 8, paddingTop: 9, paddingBottom: 8, borderRadius: 22, flexDirection: "row", alignItems: "stretch", justifyContent: "space-around", backgroundColor: "#293B51", shadowColor: "#17283B", shadowOpacity: 0.22, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 8 },
  navItem: { flex: 1, alignItems: "center", justifyContent: "center", minWidth: 52 },
  navIcon: { color: "#FFFFFF", fontSize: 25, lineHeight: 28, fontWeight: "300" },
  navIconActive: { color: "#F0A45B" },
  navLabel: { color: "#FFFFFF", fontSize: 11, fontWeight: "600", marginTop: 2 },
  navLabelActive: { color: "#F0A45B" },
});
